name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate HTML and CSS
      run: |
        docker run -v ${{ github.workspace }}:/app -w /app validator/validator:latest *.html
        docker run -v ${{ github.workspace }}:/app -w /app validator/validator:latest *.css
