name: Validate HTML and CSS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate HTML
      uses: marketplacer/w3c-validation@master
      with:
        files: |
          $(find . -name '*.html')

    - name: Install stylelint
      run: npm install stylelint stylelint-config-standard

    - name: Validate CSS
      run: |
        FILES=$(find . -name '*.css')
        if [ -n "$FILES" ]; then
          npx stylelint $FILES
        else
          echo "No CSS files found."
        fi
