name: Validate HTML and CSS

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  Validate-HTML:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: HTML Validation
      run: |
        docker run --rm -v $PWD:/workspace ghcr.io/validator/validator:latest /bin/bash -c "find /workspace -name '*.html' -exec vnu --errors-only --skip-non-html {} +"
    
    - name: Install w3c-css
      run: npm install w3c-css

    - name: CSS Validation
      run: |
        node -e "
        'use strict';
        const fs = require('fs');
        const path = require('path');
        const validator = require('w3c-css');
    
        function validateCSS(directoryPath) {
          fs.readdir(directoryPath, { withFileTypes: true }, (err, entries) => {
            if (err) {
              console.error('Error reading directory:', err);
              return;
            }
            entries.forEach(entry => {
              const fullPath = path.join(directoryPath, entry.name);
              if (entry.isDirectory()) {
                validateCSS(fullPath);
              } else if (entry.isFile() && fullPath.endsWith('.css')) {
                validator.validate(fullPath, function(err, data) {
                  if (err) {
                    console.error('Error validating:', fullPath, err);
                  } else {
                    console.log('File:', fullPath);
                    console.log('Validation errors:', data.errors);
                    console.log('Validation warnings:', data.warnings);
                  }
                });
              }
            });
          });
        }
    
        validateCSS('.');
        "


        
