name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate HTML and CSS
      uses: jakepartusch/website-validator-action@v1
      with:
        scan: 'file:///**/*.html, file:///**/*.css'
