name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate HTML
      run: |
        docker run -v ${{ github.workspace }}:/app -w /app html5validator/validator

    - name: Validate CSS
      run: |
        docker run -v ${{ github.workspace }}:/app -w /app jankx/css-validator *.css
