name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate HTML
      uses: w3c-validation-action/w3c-validation-action@v1
      with:
        file_glob: '**/*.html'

    - name: Validate CSS
      uses: w3c-validation-action/w3c-validation-action@v1
      with:
        file_glob: '**/*.css'
