name: Validate HTML and CSS

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  Validate-HTML:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: HTML Validation
      run: |
        docker run --rm -v $PWD:/workspace ghcr.io/validator/validator:latest /bin/bash -c "find /workspace -name '*.html' -exec vnu --errors-only --skip-non-html {} +"
  
  Validate-Css:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
  
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
  
    - name: Install w3c-css validator
      run: npm install -g w3c-css
  
    - name: Find CSS files
      id: css-files
      run: |
        css_files=$(find . -name '*.css' -not -path "./node_modules/*")
        css_files="${css_files//'%'/'%25'}"
        css_files="${css_files//$'\n'/'%0A'}"
        css_files="${css_files//$'\r'/'%0D'}"
        echo "::set-output name=files::$css_files"
  
    - name: Validate CSS
      run: |
        for file in ${{ steps.css-files.outputs.files }}; do
          echo "Validating $file"
          w3c-css --input "$file"
        done
