name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate HTML
      uses: docker://validator/validator:latest
      with:
        args: /github/workspace/**/*.html

    - name: Validate CSS
      uses: docker://validator/validator:latest
      with:
        args: /github/workspace/**/*.css
