name: Validate HTML and CSS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: HTML Validation
      run: |
        docker run --rm -v $PWD:/workspace ghcr.io/validator/validator:latest /bin/bash -c "find . -name '*.html' -exec vnu --errors-only --skip-non-html {} +"

    - name: Install stylelint
      run: npm install stylelint stylelint-config-standard

    - name: CSS Validation
      run: |
        FILES=$(find . -name '*.css')
        if [ -n "$FILES" ]; then
          npx stylelint $FILES
        else
          echo "No CSS files found."
        fi
